-- Generated from Kano Health Finance Tracker.xlsx. Do not edit by hand.
begin;
insert into public.entry_statuses (slug, name, description)
values
  ('pending', 'Pending', 'Submitted by an MDA user and awaiting review'),
  ('approved', 'Approved', 'Reviewed and accepted for reporting'),
  ('processed', 'Processed', 'Accepted and reconciled or posted in the finance process'),
  ('rejected', 'Rejected', 'Reviewed and rejected; excluded from official reporting')
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    active = true,
    updated_at = now();

insert into public.mda_types (slug, name)
values
  ('agency', 'Agency'),
  ('board', 'Board'),
  ('centre', 'Centre'),
  ('college', 'College'),
  ('fund', 'Fund'),
  ('hospital', 'Hospital'),
  ('ministry', 'Ministry'),
  ('school', 'School')
on conflict (slug) do update
set name = excluded.name,
    active = true,
    updated_at = now();

insert into public.mdas (code, name, mda_type_id)
values
  ('052100100100', 'Ministry of Health (HQ)', (select id from public.mda_types where name = 'Ministry')),
  ('052100300100', 'Hospital Management Board (HMB)', (select id from public.mda_types where name = 'Board')),
  ('052100300200', 'Muhammadu Abdullahi Wase Specialist Hospital (MAWSH)', (select id from public.mda_types where name = 'Hospital')),
  ('052100400100', 'College of Nursing & Midwifery Board', (select id from public.mda_types where name = 'Board')),
  ('052100400200', 'School of Nursing Kano', (select id from public.mda_types where name = 'School')),
  ('052100400300', 'School of Basic Midwifery Kano', (select id from public.mda_types where name = 'School')),
  ('052100400400', 'School of Basic Midwifery Dambatta', (select id from public.mda_types where name = 'School')),
  ('052100400600', 'School of Nursing Madobi', (select id from public.mda_types where name = 'School')),
  ('052100400700', 'School of Post Basic Anesthesia', (select id from public.mda_types where name = 'School')),
  ('052100400800', 'School of Basic Midwifery Gwarzo', (select id from public.mda_types where name = 'School')),
  ('052100500100', 'Primary Health Care Management Board (PHCMB)', (select id from public.mda_types where name = 'Board')),
  ('052100600100', 'State Agency for Control of AIDS (SACA)', (select id from public.mda_types where name = 'Agency')),
  ('052100800100', 'Kano State Contributory Health Management Agency (KCHIMA)', (select id from public.mda_types where name = 'Agency')),
  ('052100900100', 'Kano State Health Trust Fund (KHETFUND)', (select id from public.mda_types where name = 'Fund')),
  ('052101000100', 'College of Health Science & Technology', (select id from public.mda_types where name = 'College')),
  ('052101100100', 'Private Health Institutions Management Agency (PHIMA)', (select id from public.mda_types where name = 'Agency')),
  ('052101300100', 'Drugs Management & Consumable Supply Agency (DMA)', (select id from public.mda_types where name = 'Agency')),
  ('052101400100', 'Kano State Centre for Disease Control & Prevention (KNCDC)', (select id from public.mda_types where name = 'Centre')),
  ('052102000100', 'School of Hygiene', (select id from public.mda_types where name = 'School')),
  ('052103000100', 'School of Health Technology Bebeji', (select id from public.mda_types where name = 'School')),
  ('052104000100', 'School of Health Technology Kano', (select id from public.mda_types where name = 'School'))
on conflict (code) do update
set name = excluded.name,
    mda_type_id = excluded.mda_type_id,
    active = true,
    updated_at = now();

insert into public.funding_sources (slug, name)
values
  ('kano-state-govt-budget-release', 'Kano State Govt Budget Release'),
  ('bhcpf-allocation', 'BHCPF Allocation'),
  ('donors-development-partners-funding', 'Donors / Development Partners Funding'),
  ('lga-contribution', 'LGA Contribution'),
  ('nhia-nhis', 'NHIA / NHIS'),
  ('internally-generated-revenue-igr', 'Internally Generated Revenue (IGR)'),
  ('federal-government-grant', 'Federal Government Grant'),
  ('other', 'Other')
on conflict (slug) do update
set name = excluded.name,
    active = true,
    updated_at = now();

insert into public.expenditure_categories (slug, name)
values
  ('personnel-costs', 'Personnel Costs'),
  ('overhead-running-costs', 'Overhead / Running Costs'),
  ('capital-expenditure', 'Capital Expenditure'),
  ('drugs-medical-supplies', 'Drugs & Medical Supplies'),
  ('training-capacity-building', 'Training & Capacity Building'),
  ('outreach-service-delivery', 'Outreach & Service Delivery'),
  ('monitoring-evaluation', 'Monitoring & Evaluation'),
  ('community-engagement', 'Community Engagement'),
  ('infrastructure-rehabilitation', 'Infrastructure & Rehabilitation'),
  ('equipment-furniture', 'Equipment & Furniture'),
  ('transport-logistics', 'Transport & Logistics')
on conflict (slug) do update
set name = excluded.name,
    active = true,
    updated_at = now();

insert into public.programme_areas (slug, name)
values
  ('admin-general-services', 'Admin & General Services'),
  ('planning-research-statistics', 'Planning, Research & Statistics'),
  ('nursing-services', 'Nursing Services'),
  ('pharmaceutical-services', 'Pharmaceutical Services'),
  ('medical-services', 'Medical Services'),
  ('public-health-disease-control', 'Public Health & Disease Control'),
  ('physical-planning', 'Physical Planning'),
  ('hospital-services', 'Hospital Services'),
  ('family-health', 'Family Health'),
  ('disease-control', 'Disease Control'),
  ('environmental-public-health', 'Environmental & Public Health'),
  ('information-communication-technology', 'Information & Communication Technology'),
  ('health-management-programmes', 'Health Management / Programmes'),
  ('health-emergency-preparedness-response', 'Health Emergency, Preparedness & Response'),
  ('drug-supply-management', 'Drug & Supply Management'),
  ('community-health-services', 'Community Health Services'),
  ('health-financing', 'Health Financing'),
  ('human-resource-for-health', 'Human Resource for Health'),
  ('reproductive-maternal-newborn-child-health', 'Reproductive, Maternal, Newborn & Child Health'),
  ('immunisation-vaccines', 'Immunisation & Vaccines'),
  ('hiv-aids-tb-malaria', 'HIV/AIDS, TB & Malaria'),
  ('mental-health', 'Mental Health'),
  ('non-communicable-diseases', 'Non-Communicable Diseases'),
  ('other', 'Other')
on conflict (slug) do update
set name = excluded.name,
    active = true,
    updated_at = now();

insert into public.payment_methods (slug, name)
values
  ('bank-transfer', 'Bank Transfer'),
  ('cheque', 'Cheque'),
  ('cash', 'Cash'),
  ('gifmis', 'GIFMIS'),
  ('ippis', 'IPPIS'),
  ('other', 'Other')
on conflict (slug) do update
set name = excluded.name,
    active = true,
    updated_at = now();

insert into public.lgas (name)
values
  ('Ajingi'),
  ('Albasu'),
  ('Bagwai'),
  ('Bebeji'),
  ('Bichi'),
  ('Bunkure'),
  ('Dala'),
  ('Danbatta'),
  ('Dawakin Kudu'),
  ('Dawakin Tofa'),
  ('Doguwa'),
  ('Fagge'),
  ('Gabasawa'),
  ('Garko'),
  ('Garum Mallam'),
  ('Gaya'),
  ('Gezawa'),
  ('Gwale'),
  ('Gwarzo'),
  ('Kabo'),
  ('Kano Municipal'),
  ('Karaye'),
  ('Kibiya'),
  ('Kiru'),
  ('Kumbotso'),
  ('Kunchi'),
  ('Kura'),
  ('Madobi'),
  ('Makoda'),
  ('Minjibir'),
  ('Nasarawa'),
  ('Rano'),
  ('Rimin Gado'),
  ('Rogo'),
  ('Shanono'),
  ('Sumaila'),
  ('Takai'),
  ('Tarauni'),
  ('Tofa'),
  ('Tsanyawa'),
  ('Tudun Wada'),
  ('Ungogo'),
  ('Warawa'),
  ('Wudil')
on conflict (name) do update
set active = true,
    updated_at = now();

insert into public.facilities (lga_id, name, facility_type)
values
  ((select id from public.lgas where name = 'Ajingi'), 'Sakalawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Balare Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Chula Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Fagawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Gafasa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Dundun Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Gurduba Primary Health Care', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Makarya Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Toranke Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Ajingi'), 'Unguwar Bai Health Post', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Duja Health Post', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Faragai Health Post', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Gagarami Health Post', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Hungu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Panda Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Saya Saya Primary Health Center (ALB)', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Tsangaya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Daho Health Post', 'phc'),
  ((select id from public.lgas where name = 'Albasu'), 'Bataiya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Abbas Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Dangada Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Gadanya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Gogori Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Kiyawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Kwajale Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Romo Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Sare-Sare Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Wuro-Bagga Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bagwai'), 'Rimin Dako Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Anadariya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Kuki Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Jibga Health Post (Bebeji)', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Baguda Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Damau Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Durmawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Gargai Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Gwarmai Primary Health Centre (Bebeji)', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Kofa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Rahama (B) Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Ranka Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Wak Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Tariwa Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Bebeji'), 'Rantan Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Danzabuwa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Fagwalo Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Dutsen Karya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Kwamarawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Chiromawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Muntsira Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Saye Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Waire Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Damargu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bichi'), 'Badume Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Bunkure Basic Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Chirin Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Gafan Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Gurjiya Primary Health Care', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Gwamma Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Kulluwa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Sanda Health Post', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Bono Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Bunkure'), 'Barkum Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Adakawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Bakin Ruwa Basic Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Mai Unguwa Garba Dala Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Goron Dutse Primary Health Centre (Dal)', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Kurna Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Gwammaja Maternity And Child Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Dala Primary Health Care Centre', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Kantudu Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Kofar Mazugal Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Dandinshe Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Madigawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dala'), 'Yalwa Primary Health Centre (DAL)', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Ajumawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Women Centre Health Post', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Fagwalo Health Post', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Tona Health Post', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Goron Maje Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Gwanda Primary Health Centre (Dambatta)', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Gwarabjawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Kore Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Danbatta'), 'Sansan Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Daba Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Runa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Dawaki Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Dawakiji Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Kamgata Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Gano Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Gurjiya Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Jido Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Gada Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Tsakuwa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Unguwar Duniya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Sarai Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Yankatsari Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Yargaya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Kudu'), 'Zogarawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Danguguwa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Sarkakiya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Dawanau Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Ganduje Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Gargari Health Post', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Jalli Health Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Kwa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Marke Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Tattarawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Dawakin Tofa'), 'Dandalama Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Dariyar Shere Health Post', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Burji Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Bamako Initiative Health Post', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Falgore Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Maraku Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Dadin-Kowa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Riruwai Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Tagwaye Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Unguwar Natsohuwa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Doguwa'), 'Zainabi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Sabo Garba Maternal and Child Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Galadima Fagge Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Wapa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Fatima Ganduje Primary Health Care', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Kwacire Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Rijiyar Lemo Model Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Jaba Model Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Middle Road Maternity and Child Health', 'phc'),
  ((select id from public.lgas where name = 'Fagge'), 'Sheik Musa Kallah Primary Health Care', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Gabasawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Garun Danga Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Santsi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Karmami Maternal And Child Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Mekiya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Tarauni Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'YanDake Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'YautarKudu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Yama Kanawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Zakirai Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gabasawa'), 'Zugachi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Dal Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Garin-Ali Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Garko Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Gurjiya Health Post (GAK)', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Kafin Malami Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Sanni Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Buda Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Garwaji Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Sarina Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garko'), 'Kafinchiri Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Chiromawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Dakasoye Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Dorawar Sallau Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Yanaba Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Garun Babba Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Garun Mallam Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Jobawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Kadawa Gate Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Makwaro Health Post', 'phc'),
  ((select id from public.lgas where name = 'Garum Mallam'), 'Yadakwari Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Balan Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Gamarya Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Gamoji Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Rabiu Musa Kwankwaso Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Nafisatu Mahammud Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Kademi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Yankau Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Gidan Sarkin Noma Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Yan Audu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gaya'), 'Gungara Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Babawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Gofaro Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Gezawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Jogana Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Tsamiyar Kara Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Mesar Burmi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Sararin Gezawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Larabar Abasawa Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Tumbau Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Wangara Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gezawa'), 'Tsalle Primary Health Care Centre', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Diso Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Ja''En Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Fuskar Yamma Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Gwaron Dutse Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Mangorori Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Kabuga Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Sabon Sara Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gwale'), 'Kwamatin Makota Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Getso Cottage Hospital', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Yar Kasuwa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Jama''a Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Sabon Layin Kara Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Kutama Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Lakwaya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Madadi Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Mainika Health Post', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Sabon Birni Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Gwarzo'), 'Kwami Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Dugabau Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'DurunMCH', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Gammo Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Garo Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Godiya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Gude Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Hauwaden Bango Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Mallam Gajere Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Kanwa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kabo'), 'Masanawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Chedi Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Dan Agundi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Gandu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Unguwar Gini Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Fuskar Gabas Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Sharada Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Datti Wudilawa Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Emir''s Palace Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Zubairiyya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kano Municipal'), 'Yan Awaki Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Daura Health Post', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Husama Health Post', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Kurugu Health Post', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Kwanyawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Tinkis Health Post', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Karaye Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Tudun Kaya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Turawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Yammedi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Karaye'), 'Yola Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Durba Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Kure Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Saya Saya Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Kadigawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Kahu Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Kibiya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Gunda Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Nariya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Tarai Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Kibiya'), 'Unguwar Gai Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Ba''awa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Badafi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Bargoni Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Bauda Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Dangora Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Dansoshiya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Dashi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Galadimawa Health Post (KKU)', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Kiru Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Kogo Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Maraku Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Tsaudawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'YakoBasic Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Kafin Maiyaki Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kiru'), 'Zuwo Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Chalawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Chiranchi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Dan Maliki Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Danbare Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Guringawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Ruga Fada Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'AhmedAdoBayero Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Mariri Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Naibawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Panshekara Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kumbotso'), 'Unguwar Rimi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Unguwar Gyartai Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Gidan Nisau Heath Post', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Gwarmai Primary Health Centre (c)', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Kasuwar Kuka Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Kunchi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Matan Fada Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Ridawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Gwadama Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Shuwaki Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kunchi'), 'Yan Dadi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Hadeja Jama''are Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Dan-Hassan Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Dukawa Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Gundutse Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Karfi Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Sani Marshal Memorial Maternity Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Kirya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Alkalawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'TanawaA Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'TanawaB Health Post', 'phc'),
  ((select id from public.lgas where name = 'Kura'), 'Imawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Burji Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Chinkoso Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Galinja Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Gora Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Kafin Agur Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Kanwa Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Kauran Mata Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Kubarachi Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Daburau Health Post', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Akilu Memorial Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Rikadawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Madobi'), 'Yakun Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Dr. Wada Waziri Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Tasharbasa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Jibga Health Post', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Kantudu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Koguna Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Mai-Tsidau Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Makoda Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'DawanKaya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Tangajiyo Health Post', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'Wailare Health Post', 'phc'),
  ((select id from public.lgas where name = 'Makoda'), 'KorenTabo Health Post', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Sanbauna Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Gadurwawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Geranya Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Kunya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Kuru Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Gasgainu Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Minjibir Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Sarbi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Tsakiya Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Kankarawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Minjibir'), 'Wasai Health Post', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Dawakin Dakata Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Gama Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Gwagwarwa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Giginyu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Hotoro Arewa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Hotoro South Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Kaura Goje Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Kawaji Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Tudun Murtala Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Nasarawa'), 'Kano School of Health Technology Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Lausu Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Madachi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Kurmi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Rano Dawaki Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Munture Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Rurum Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Rurum Sabon Gari Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Saji Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Yalwa Health Post (Ran)', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Taitai Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rano'), 'Tabobi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Butu Butu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Dawakin Gulu Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Doka-Dawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Dugurawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Gulu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Jili Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Karofin Yashi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Rimin Gado Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Sakaratsa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Tamawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Yalwa-Danziyal Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Rimin Gado'), 'Zango1 Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Beli Primary Health  Center', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Falgore Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Fulatan Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Bari Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Jajaye Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Rogo Tsohuwa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Kauyen Liman Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Ruwan Bago Health Post', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Zarewa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Rogo'), 'Kaleku Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Alajawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Dutsen Bakoshi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Faruruwa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Goron Dutse Health Post  (Snn)', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Kadamu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Kokiya Health Post', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Leni Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Shakogi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Shanono Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Shanono'), 'Tsaure Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Gala Primary Health  Center', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Gani Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Garfa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Gediya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Kanawa Primary Health  Center', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Magami Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Massu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Rimi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Rumo Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Sitti Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Sumaila'), 'Sumaila Yamma Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Birnin Bako Health Post', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Durbinde Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Fajewa Model Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Falali Health Post', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Dambazau Primary HealthC entre  (TAK)', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Kachako Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Karfi Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Kafinsidda Health Post', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Takai Nysc Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Takai'), 'Zuga Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Hausawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Dan Tsinke Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Daurawa Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Ja''Oji Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Gyadi-GyadiKudu Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Hotoro Danmarke Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Tarauni Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Unguwa Uku Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'Kauyen Alu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tarauni'), 'YarAkwa Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Dindere Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Doka Primary Health  Center', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Gadija Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Ginsawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Janguza Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Bugai Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Kwami Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Lambu Primary Health  Center', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Langel Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Tofa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Unguwar Rimi Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Tabanni Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Yalwa Karama Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Yanoko Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tofa'), 'Yarimawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Daddarawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Dumbulum Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Tafashiya Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Gurun Primary Health Care Centre', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Harbau Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Yargwanda Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Tsanyawamodal Primary Health  Center', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Yan-kamaye Primary Health  Center', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Yanganau Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tsanyawa'), 'Zarogi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'Yaryasa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'Jan Dutse Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'NaTa''Ala Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'Dalawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'Baburi Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'Karefa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'Kurkujawa Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'RuguRugu Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Tudun Wada'), 'Jan Maje Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Dantamashe Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Gayawa Basic Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Panisau Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Bachirawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Inusawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Kadawa Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Bagujan Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Zaura Babba Health Post', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Rijiyar Zaki Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Ungogo Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Ungogo'), 'Tudun Fulani Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Alitini Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Warawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'YanDalla Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Tanagar Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Danlasan Primary Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Katarkawa Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'JumarGaladima Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Ganakakun Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Jemagu Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Amarawa Health Post (Wra)', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Tamburawar Gabas Primary Health Center', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Jigawa Health Post (WRA)', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Garin Dau Health Post', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Imawa Health Post (WRA)', 'phc'),
  ((select id from public.lgas where name = 'Warawa'), 'Gogel Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Utai Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Wudil Health Post', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Makanwachi Health Post', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Lajawa Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Kausani Health Clinic', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Indabo Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Achika Health Post', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Darki Primary Health Centre', 'phc'),
  ((select id from public.lgas where name = 'Wudil'), 'Dagumawa Health Post', 'phc')
on conflict (lga_id, name) do update
set facility_type = excluded.facility_type,
    active = true,
    updated_at = now();

commit;
